// <auto-generated />
using ClassS00219971.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassS00219971.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("ClassS00219971.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "8 Johnstown Road, Cork",
                            CreditRating = 200m,
                            Name = "Patricia McKenna"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Garden House Crowther Way, Dublin",
                            CreditRating = 400m,
                            Name = "Helen Bennett"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1900 Oak St., Vancouver",
                            CreditRating = 2000m,
                            Name = "Yoshi Tanami"
                        },
                        new
                        {
                            Id = 4,
                            Address = "12 Orchestra Terrace, Dublin 20",
                            CreditRating = 800m,
                            Name = "John Steel"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rue Joseph-Bens 532, Brussels",
                            CreditRating = 600m,
                            Name = "Catherine Dewey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
